### ISSUE TITLE
[2023-Q2/04-06]: 第二季度计划

### ISSUE THREAD

**Issue by skypesky** [skypesky/study#404]
# 1. 阅读书籍(完成前2）

- [x] https://github.com/skypesky/study/issues/345
- [ ] #354
---
- [ ] #106 
- [ ] #244
- [ ] #364
- [ ] #226
- [ ] #343 

# 2. 英语技能(完成前1）

- [ ] #8

# 3. 编程技能(完成前4）

- [x] https://github.com/skypesky/study/issues/369
- [x] https://github.com/skypesky/study/issues/433
- [x] #55
- [x] #212
- [x] #74 
- [x] #236
- [x] #272
- [ ] https://github.com/skypesky/study/issues/304
- [ ] #13
- [ ] https://github.com/skypesky/study/issues/353
---
- [ ] #205 
- [ ] #82 
- [ ] #289 
- [ ] https://github.com/skypesky/study/issues/315
- [ ] #290 
- [ ] https://github.com/skypesky/study/issues/370
- [ ] #14
- [ ] #76

# 4. 生活

## 4.1 学习做菜 :joy:

- [ ] #4
- [ ] #5

## 4.2 健康

- [ ] #347

# 5. software

- [ ] #346 
- [ ] https://github.com/skypesky/study/issues/340
