### ISSUE TITLE
[2023-Q3/07-09]: 第三季度计划

### ISSUE THREAD

**Issue by skypesky** [skypesky/study#448]
# 1. 阅读书籍(完成前2）

# 2. 英语技能(完成前1）

- [ ] skypesky/study#8

# 3. 编程技能(完成前4）

- [x] https://github.com/skypesky/study/issues/304
- [x] skypesky/study#442 
- [x] https://github.com/skypesky/study/issues/370
- [x] skypesky/study#76

# 4. 生活

## 4.2 健康

# 5. software

- [x] https://github.com/skypesky/study/issues/340
