### ISSUE TITLE
[Epic]: 原神

### ISSUE THREAD

**Issue by skypesky** [skypesky/study#463]
# 角色培养

## 圣遗物
- [ ] 绝缘本
- [ ] 回声之林夜话
- [ ] 冰本

## 配队

- 种门
- [ ] 提纳里
- [ ] 芙宁娜
- [ ] 久岐忍
- [ ] 行秋
- 雷神国家队
- [ ] 雷神
- [ ] 行秋
- [ ] 班尼特
- [ ] 香菱
- undefined
- [ ] 神里凌华
- [ ] 罗萨莉亚
- [ ] 芭芭拉
- [ ] 砂糖
- other
- [ ] 神里凌华
- [ ] 行秋
- [ ] 班尼特
- [ ] 香菱
- [ ] 重云
- [ ] 提纳里
- [ ] 砂糖
- [ ] 久岐忍
- [ ] 芙宁娜

## 探索度

- [ ] 沉玉谷: https://www.bilibili.com/video/BV1n24y187vK/?spm_id_from=333.788.top_right_bar_window_history.content.click&vd_source=02f69fddce3709fc1d0a26a832b2163d
- [ ] 邀约事件: https://www.bilibili.com/video/BV1n24y187vK/?spm_id_from=333.788.top_right_bar_window_history.content.click&vd_source=02f69fddce3709fc1d0a26a832b2163d
- [ ] 须弥一条龙: https://www.bilibili.com/video/BV1te4y1C7LT?p=19&vd_source=02f69fddce3709fc1d0a26a832b2163d

## 2024/01/22~2024/01/28

assign to lotta

- [x] 雷电将军突破材料(天云草实 3/?? 收集 75 个) => 预计 45 min
- [x] 久岐忍突破材料(鸣草 17/?? 收集 90 个) => 预计 45 min 
- [x] 水神突破材料(湖光铃兰 2/60) => 预计 45 min

## 2024/01/08~2024/01/14

assign to lotta

- [x] 娜维娅80级突破素材(初露之源,异色结晶石 => progress)
- [x] 钟离80级突破材料(石珀)
- [x] 香菱80级突破材料(绝云椒椒 => progress)
- [x] 久岐忍60级突破材料(鸣草 => progress)
- [x] 两天的日常委托(不要用奖励的,可以开宝箱)
- [x] 活动打一打,最好达到6000分,我没法满星

## 2023/12/25 ~2023/12/31

assign to lotta

- [x] 活动的极限驱策法(这玩意要组队,我不想打,其他的我都打了)
- [x] 提纳里等级突破材料(月莲)
- [x] 鱼获精炼材料
- [x] 升级尘歌壶(目标8级): 你看看哪些东西可以提升等级的,木材我都砍了

## 2023/12/18~2023/12/24

assign to lotta
- [x] 升级尘歌壶(目标8级): 有几种木材我没砍过，砍一下
- [x] 鱼获精炼材料
- [x] 神里绫华等级突破材料: 只要手动绣球就行
- [x] 活动的极限驱策法

**Comment by skypesky** [comment]
深渊已经可以轻松满星了。
